### ISSUE TITLE
kIRG_xSource :mapping is a code point?

### ISSUE THREAD

**Issue by kipcole9** [elixir-unicode/unicode_unihan#5]
```elixir
  kIRG_GSource: %{mapping: ["3E3C"], source: "G5"},
  kIRG_KSource: %{mapping: "236A", source: "K3"},
  kIRG_TSource: %{mapping: "5A7D", source: "T4"},
```
Are these `:mapping` fields code points?  Should they therefore be converted to integers to be consistent?  If so I'm fine to make the change, just let me know.

**Comment by jkwchui** [comment]
Yes, please.

I was actually not sure when I did the first pass, which is why I didn’t
convert them.

My (still limited) understanding is that different national bodies
(ideographic research group IRG) recommend inclusion of particular CJK
ideographs; and they support these recommendations with primary sources
(`source`).  Each recommendation is given a… ticket number, and that
ideograph retains the number (zero-padded 5-digit decimal) regardless of
whether it survived vetting.  I’m not sure why they have chosen to compress
this into a hex-“mapping”… but given its provenance, converting to base-10
is probably appropriate.

Jon

**Comment by kipcole9** [comment]
I do not know how you keep your head clear on this - it makes my head hurt!  But .... I know how to convert hex to integer so I'll take care of that :-)

**Comment by kipcole9** [comment]
Turns out not all of the mapping data is hex digits so I'll close this for now.
